apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  type: NodePort
  ports:
  - name: "server-service"
    port: 8228
    targetPort: 8228
    nodePort: 31001
  selector:
    app: server
